In [38]:
import pandas as pd
data_frame = pd.read_csv("ODI Player Innings Stats - All Teams.csv")
data_frame.count()

C:\Users\S533718\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (0,1,2,6,7,8,9,10,11,12,13,14,17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Innings Player                   85774
Innings Runs Scored              85774
Innings Runs Scored Num          85774
Innings Minutes Batted           85774
Innings Batted Flag              85774
Innings Not Out Flag             85774
Innings Balls Faced              85774
Innings Boundary Fours           85774
Innings Boundary Sixes           85774
Innings Batting Strike Rate      85774
Innings Number                   85774
Opposition                       85774
Ground                           85774
Innings Date                     85774
Country                          85774
50's                             85774
100's                            85774
Innings Runs Scored Buckets      85774
Innings Overs Bowled                 0
Innings Bowled Flag                  0
Innings Maidens Bowled               0
Innings Runs Conceded                0
Innings Wickets Taken                0
4 Wickets                            0
5 Wickets                            0
10 Wickets               

In [44]:
data_copy_1 = data_frame.copy()
data_copy_1.dropna(axis='index', how='all', inplace=True)
data_copy_1.info()

data_copy_2 = data_copy_1.copy()
data_copy_2.drop(labels="Innings Overs Bowled", axis='columns', inplace=True)
data_copy_2.drop(labels="Innings Bowled Flag", axis='columns', inplace=True)
data_copy_2.drop(labels="Innings Maidens Bowled", axis='columns', inplace=True)
data_copy_2.drop(labels="Innings Runs Conceded", axis='columns', inplace=True)
data_copy_2.drop(labels="Innings Wickets Taken", axis='columns', inplace=True)
data_copy_2.drop(labels="4 Wickets", axis='columns', inplace=True)
data_copy_2.drop(labels="5 Wickets", axis='columns', inplace=True)
data_copy_2.drop(labels="10 Wickets", axis='columns', inplace=True)
data_copy_2.drop(labels="Innings Wickets Taken Buckets", axis='columns', inplace=True)
data_copy_2.drop(labels="Innings Economy Rate", axis='columns', inplace=True)
data_copy_2.drop(labels="Innings Runs Scored Buckets", axis='columns', inplace=True)
indexNames = data_copy_2[ (data_copy_2['Innings Minutes Batted'].isin(["-"])) ].index
data_copy_2.drop(indexNames , inplace=True)
data_copy_3 = data_copy_2.dropna(subset=['Innings Balls Faced'])
data_copy_4=data_copy_3.replace(to_replace ="-",value = 0)
print(data_copy_2.info())
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(data_copy_4, test_size=0.4, random_state=123)
len(train_set)


<class 'pandas.core.frame.DataFrame'>
Int64Index: 85774 entries, 0 to 85773
Data columns (total 28 columns):
Innings Player                   85774 non-null object
Innings Runs Scored              85774 non-null object
Innings Runs Scored Num          85774 non-null object
Innings Minutes Batted           85774 non-null float64
Innings Batted Flag              85774 non-null float64
Innings Not Out Flag             85774 non-null float64
Innings Balls Faced              85774 non-null object
Innings Boundary Fours           85774 non-null object
Innings Boundary Sixes           85774 non-null object
Innings Batting Strike Rate      85774 non-null object
Innings Number                   85774 non-null object
Opposition                       85774 non-null object
Ground                           85774 non-null object
Innings Date                     85774 non-null object
Country                          85774 non-null object
50's                             85774 non-null float64
100's  

51464

In [45]:
from sklearn.tree import DecisionTreeClassifier
X = train_set[['Innings Balls Faced']]
y = train_set['Innings Runs Scored Num']
y = y.astype('int')
tree_classifier = DecisionTreeClassifier()
tree_classifier.fit(X,y)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

# Discussion

I chose 'Innings Balls Faced' and 'Innings Runs Scored Num' as my X and Y as these features can be used to prediction

In [46]:
from sklearn.tree import DecisionTreeClassifier
X = train_set[['Innings Balls Faced']]
Y = train_set['Innings Runs Scored Num']
Y = Y.astype('int')
tree_classifier = DecisionTreeClassifier()
print(tree_classifier.fit(X,Y))
from sklearn.metrics import confusion_matrix
y_predicted = tree_classifier.predict(X)
matrix = confusion_matrix(Y, y_predicted)
print("Confusion Matrix",matrix)
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np
print ("Accuracy is ", accuracy_score(Y, y_predicted))
print ("Sensitivity is ", recall_score(Y, y_predicted, average="weighted"))
print ("Precision is ", precision_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))
print ("F1 is ", f1_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
Confusion Matrix [[14154   466    62 ...     0     0     0]
 [ 1389   552   116 ...     0     0     0]
 [  656   506   142 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]
Accuracy is  0.3277048033576869
Sensitivity is  0.3277048033576869
Precision is  0.3497037171560019
F1 is  0.3592054337154524


# Discussion
The accuracy is 0.32, Sesnsitivity is 0.32, Precision is  0.34, F1 is  0.35. As the accuracy is less the modal is not so good.

In [47]:
from sklearn.svm import SVC
X = train_set[['Innings Balls Faced']].head(15000)
Y = train_set['Innings Runs Scored Num'].head(15000)
Y = Y.astype('int')
svm_classifier = SVC(kernel='rbf')
print(svm_classifier.fit(X,Y))
y_predicted = svm_classifier.predict(X)
matrix = confusion_matrix(Y, y_predicted)
print("Confusion Matrix",matrix)
print ("Accuracy is ", accuracy_score(Y, y_predicted))
print ("Sensitivity is ", recall_score(Y, y_predicted, average="weighted"))
print ("Precision is ", precision_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))
print ("F1 is ", f1_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))

C:\Users\S533718\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Confusion Matrix [[4175   78    0 ...    0    0    0]
 [ 429   95    0 ...    0    0    0]
 [ 258   84    0 ...    0    0    0]
 ...
 [   0    0    0 ...    1    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]
Accuracy is  0.3394
Sensitivity is  0.3394
Precision is  0.3360988459472418
F1 is  0.3611921480814234


In [48]:
from sklearn.svm import SVC
X = train_set[['Innings Balls Faced']].head(500)
Y = train_set['Innings Runs Scored Num'].head(500)
Y = Y.astype('int')
svm_classifier = SVC(kernel='rbf')
print(svm_classifier.fit(X,Y))
y_predicted = svm_classifier.predict(X)
matrix = confusion_matrix(Y, y_predicted)
print("Confusion Matrix",matrix)
print ("Accuracy is ", accuracy_score(Y, y_predicted))
print ("Sensitivity is ", recall_score(Y, y_predicted, average="weighted"))
print ("Precision is ", precision_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))
print ("F1 is ", f1_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Confusion Matrix [[133   9   0 ...   0   0   0]
 [  7  12   0 ...   0   0   0]
 [  3   3   0 ...   0   0   0]
 ...
 [  0   0   0 ...   1   0   0]
 [  0   0   0 ...   0   1   0]
 [  0   0   0 ...   0   0   1]]
Accuracy is  0.498
Sensitivity is  0.498
Precision is  0.573838919266309
F1 is  0.5865981868577721


C:\Users\S533718\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [49]:
X = test_set[['Innings Balls Faced']].head(200)
Y = test_set['Innings Runs Scored Num'].head(200)
Y = Y.astype('int')
svm_classifier = SVC(kernel='rbf')
print(svm_classifier.fit(X,Y))
y_predicted = svm_classifier.predict(X)
matrix = confusion_matrix(Y, y_predicted)
print("Confusion Matrix",matrix)
print ("Accuracy is ", accuracy_score(Y, y_predicted))
print ("Sensitivity is ", recall_score(Y, y_predicted, average="weighted"))
print ("Precision is ", precision_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))
print ("F1 is ", f1_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Confusion Matrix [[53  2  0 ...  0  0  0]
 [ 2  3  1 ...  0  0  0]
 [ 1  2  4 ...  0  0  0]
 ...
 [ 0  0  0 ...  1  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0  1]]
Accuracy is  0.64
Sensitivity is  0.64
Precision is  0.7199919593661446
F1 is  0.7101308467567834


C:\Users\S533718\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [50]:
X = test_set[['Innings Balls Faced']].head(200)
Y = test_set['Innings Runs Scored Num'].head(200)
Y = Y.astype('int')
svm_classifier = SVC(kernel='sigmoid')
print(svm_classifier.fit(X,Y))
y_predicted = svm_classifier.predict(X)
matrix = confusion_matrix(Y, y_predicted)
print("Confusion Matrix",matrix)
print ("Accuracy is ", accuracy_score(Y, y_predicted))
print ("Sensitivity is ", recall_score(Y, y_predicted, average="weighted"))
print ("Precision is ", precision_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))
print ("F1 is ", f1_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Confusion Matrix [[55  0  0 ...  0  0  0]
 [ 8  0  0 ...  0  0  0]
 [ 7  0  0 ...  0  0  0]
 ...
 [ 0  1  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]]
Accuracy is  0.275
Sensitivity is  0.275
Precision is  0.4001322751322751
F1 is  0.5487528344671202


C:\Users\S533718\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [51]:
X = test_set[['Innings Balls Faced']].head(200)
Y = test_set['Innings Runs Scored Num'].head(200)
Y = Y.astype('int')
svm_classifier = SVC(kernel='linear')
print(svm_classifier.fit(X,Y))
y_predicted = svm_classifier.predict(X)
matrix = confusion_matrix(Y, y_predicted)
print("Confusion Matrix",matrix)
print ("Accuracy is ", accuracy_score(Y, y_predicted))
print ("Sensitivity is ", recall_score(Y, y_predicted, average="weighted"))
print ("Precision is ", precision_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))
print ("F1 is ", f1_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Confusion Matrix [[53  2  0 ...  0  0  0]
 [ 4  2  0 ...  0  0  0]
 [ 2  5  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  1  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0  0]]
Accuracy is  0.39
Sensitivity is  0.39
Precision is  0.5629425309086327
F1 is  0.6035219439294142


In [52]:
from sklearn.svm import SVC
X = test_set[['Innings Balls Faced','Innings Minutes Batted']].head(5000)
Y = test_set['Innings Runs Scored Num'].head(5000)
Y = Y.astype('int')
svm_classifier = SVC(kernel='rbf')
print(svm_classifier.fit(X,Y))
y_predicted = svm_classifier.predict(X)
matrix = confusion_matrix(Y, y_predicted)
print("Confusion Matrix",matrix)
print ("Accuracy is ", accuracy_score(Y, y_predicted))
print ("Sensitivity is ", recall_score(Y, y_predicted, average="weighted"))
print ("Precision is ", precision_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))
print ("F1 is ", f1_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))

C:\Users\S533718\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Confusion Matrix [[1370   41   15 ...    0    0    0]
 [  96  106   14 ...    0    0    0]
 [  33   45   46 ...    0    0    0]
 ...
 [   0    0    0 ...    1    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    1]]
Accuracy is  0.5726
Sensitivity is  0.5726
Precision is  0.5998557901584528
F1 is  0.5713163272613105


As there are too many data values I'm choosing just few of them and also the Support Vector Machine performs well on the smaller data values.